on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Publish current state'
  push:
    branches:
      - main
    ignore-paths:
      - node_modules/**
    paths:
      - '**/*-color-theme.json'
      - '**/*-icon-theme.json'

name: Publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'bump version'
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: ''
      - uses: lannonbr/vsce-action@master
        with:
          args: 'publish -p $VSCE_TOKEN'
        env:
          VSCE_TOKEN: ${{ secrets.PAT }} # This exists in github settings
